vich_uploader:
  db_driver: orm
  mappings:
    module_file:
      uri_prefix: /uploads/modules
      upload_destination: "%kernel.project_dir%/public/uploads/modules"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    pdf_file:
      uri_prefix: /uploads/pdfs
      upload_destination: "%kernel.project_dir%/public/uploads/pdfs"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
