vich_uploader:
  db_driver: orm
  storage: file_system
  mappings:
    module_file:
      uri_prefix: /uploads/modules
      upload_destination: "%kernel.project_dir%/public/uploads/modules"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
