# config/services.yaml
parameters:

services:
  # Default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: "%kernel.project_dir%"

  # Makes classes in src/ available to be used as services
  # This creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Kernel.php" # On retire ../src/Entity/ de l'exclusion

  # Explicit configuration for EmailVerifier service
  App\Security\EmailVerifier:
    arguments:
      $verifyEmailHelper: '@SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface'

  App\Service\FileUploader:
    arguments:
      $targetDirectory: "%modules_directory%"

  App\Twig\AppExtension:
    tags: ["twig.extension"]
